const express=require("express");
const router=express.Router();
const c=require("../controller/academicController");
const wrapAsync=require("../utils/wrapAsync");
const isLoggedIn=require("../middleware/isLoggedIn");
const isAdmin=require("../middleware/isAdmin");
router.get("/find-books",wrapAsync(c.findBooks));
router.get("/academic/options",wrapAsync(c.options));
router.post("/book-requests/:id",isLoggedIn,wrapAsync(c.requestBook));
router.get("/book-requests",isLoggedIn,wrapAsync(c.myRequests));
router.get("/my-academic-books",isLoggedIn,wrapAsync(c.myBooks));
router.post("/my-academic-books/:id/relist",isLoggedIn,wrapAsync(c.relist));
router.get("/admin/academic",isAdmin,wrapAsync(c.adminIndex));
router.post("/admin/academic",isAdmin,wrapAsync(c.adminCreate));
router.delete("/admin/academic/:id",isAdmin,wrapAsync(c.adminDelete));
module.exports=router;